# This theme is based on Catppuccin Latte (Copyright (c) 2021 Catppuccin, released
# under the MIT license, https://github.com/catppuccin/catppuccin)

# comments
"comment" = "#7c7f93"

# strings
"string" = "#40a02b"

# regular expressions
"keyword.operator.regexp" = "#ea76cb"

# escape characters
"constant.character" = "#ea76cb"

# constants in general
"constant" = "#fe640b"

# parameters
"variable.parameter" = "#e64553"

# environment variables
"variable.other" = "#d20f39"
"punctuation.definition.variable" = "#d20f39"

# commands
"variable.function" = "#1e66f5"

# home directory ~
"variable.language.tilde" = "#d20f39"

# keywords
"keyword" = "#8839ef"

# general foreground color
"source" = "#4c4f69"

# variable assignments
"storage" = "#df8e1d"
"storage.modifier" = "#8839ef"

# support terms (e.g. double braces, let)
"support" = "#1e66f5"
"keyword.operator" = "#179299"

# function names
"entity.name.function" = "#1e66f5"

# braces
"punctuation.section" = "#7c7f93"

# terminators (e.g. ";;" after a case item)
"punctuation.terminator" = "#7c7f93"

# history expansions
"meta.group.expansion.history" = "#d20f39"

# reset command substitutions to the theme's default foreground color
"meta.group.expansion.command.parens" = { foreground = "#4c4f69" }

# dynamic items
"dynamic.callable" = "#1e66f5"
"dynamic.callable.missing" = "#d20f39"
"dynamic.path" = { underline = true }
