# Based on the colors from https://github.com/rebelot/kanagawa.nvim/

"comment" = "#727169"
"constant.character.escape" = "#c0a36e"
"constant.numeric" = "#d27e99"
"dynamic" = "#6a9589"
"dynamic.callable.alias.shell" = "#7aa89f"
"dynamic.callable.builtin.shell" = "#7fb4ca"
"dynamic.callable.missing.shell" = "#c34043"
"dynamic.path" = { underline = true }
"entity.name.function" = "#7e9cd8"
"invalid" = "#e82424"
"keyword" = "#957fb8"
"keyword.control.case.item.shell" = "#9cabca"
"keyword.control.regexp" = "#9cabca"
"keyword.operator" = "#c0a36e"
"keyword.operator.logical.continue.shell" = "#9cabca" # semicolon
"meta" = "#7fb4ca"
"meta.function-call.arguments.shell" = "#b8b4d0"
"meta.group.expansion.brace.shell" = "#c0a36e"
"meta.regexp.shell" = "#c0a36e"
"punctuation" = "#9cabca"
"punctuation.definition.comment.begin.shell" = "#727169"
"punctuation.definition.string" = "#98bb6c"
"punctuation.definition.variable.shell" = "#7fb4ca"
"punctuation.section.expansion" = "#7fb4ca"
"punctuation.section.parens" = "#7fb4ca"
"storage" = "#957fb8"
"string" = "#98bb6c"
"support" = "#9cabca"
"variable" = "#dcd7ba"
"variable.language" = "#e46876"
"variable.language.tilde.shell" = "#b8b4d0"
"variable.parameter.option.shell" = "#9cabca"
