# This theme is based on Tokyo Night (Copyright (c) 2018-present Enkia, released
# under the MIT license, https://github.com/tokyo-night/tokyo-night-vscode-theme)

"comment" = "#9CA3B3"
"string" = "#9ECE6A"
"keyword.operator.regexp" = "#9ECE6A"
"constant.character.escape" = "#E6C384"
"constant.numeric.integer.decimal.file-descriptor" = "#E6C384"
"variable.parameter" = "#BB9AF7"
"variable.other" = "#E6C384"
"punctuation.definition.variable" = "#E6C384"
"variable.function" = "#7DCFFF"
"variable.language.tilde" = "#BB9AF7"
"keyword" = "#7AA2F7"
"storage" = "#7AA2F7"
"support" = "#7DCFFF"
"entity.name.function" = "#E6C384"
"punctuation.section" = "#E6C384"

# dynamic items
"dynamic.callable" = "#7DCFFF"
"dynamic.callable.missing" = "#F7768E"
"dynamic.path" = { underline = true }
