name: CI

on:
  pull_request:
  push:

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # Install Rust
      - name: Install MSRV
        uses: dtolnay/rust-toolchain@stable

      # Cache Rust/Cargo build artifacts
      - uses: Swatinem/rust-cache@v2

      # Get MSRV from Cargo.toml
      - name: Extract metadata
        id: extract_metadata
        run: |
          cargo metadata --no-deps --format-version 1 | jq -r '"msrv=" + .packages[0].rust_version' | tee -a $GITHUB_OUTPUT
      
      # Test with MSRV
      - name: Install MSRV
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.extract_metadata.outputs.msrv }}
      - name: Run tests
        run: cargo --version && cargo test

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # Install Rust
      - uses: dtolnay/rust-toolchain@stable

      # Cache Rust/Cargo build artifacts
      - uses: Swatinem/rust-cache@v2

      # Run integration tests
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          file: tests/Dockerfile
          push: false
          load: true # make image available locally
          tags: michelkraemer/zsh-patina-test-dev:latest
          build-args: |
            "PROFILE=dev"
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run integration tests
        env:
          USE_PREBUILT_IMAGE: true
        run: cargo test -- --ignored

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # Install Rust
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt,clippy

      # Cache Rust/Cargo build artifacts
      - uses: Swatinem/rust-cache@v2

      # Check code
      - run: cargo fmt -- --check
      - run: cargo clippy

      # Build and smoke test
      - name: Build
        run: cargo b -r
      - name: List scopes
        run: target/release/zsh-patina list-scopes
      - name: Tokenize
        run: echo 'for i in 1 2 3; do echo $i; done' | target/release/zsh-patina tokenize
