# This file is partly based on the workflows from bat (https://github.com/sharkdp/bat/)
# and ripgrep (https://github.com/BurntSushi/ripgrep). bat is released under the
# MIT license (Copyright (c) 2018-2023 bat-developers) and ripgrep under the
# Unlicense.

name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  check-version:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - name: Get the release version from the tag
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Check that tag version and Cargo.toml version are the same
        shell: bash
        run: |
          if ! grep -q "version = \"$VERSION\"" Cargo.toml; then
            echo "version does not match Cargo.toml" >&2
            exit 1
          fi
    outputs:
      version: ${{ env.VERSION }}

  crate-metadata:
    needs: ['check-version']
    name: Extract crate metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Extract crate information
        id: crate-metadata
        run: |
          cargo metadata --no-deps --format-version 1 | jq -r '"name=" + .packages[0].name' | tee -a $GITHUB_OUTPUT
          cargo metadata --no-deps --format-version 1 | jq -r '"version=" + .packages[0].version' | tee -a $GITHUB_OUTPUT
          cargo metadata --no-deps --format-version 1 | jq -r '"maintainer=" + .packages[0].authors[0]' | tee -a $GITHUB_OUTPUT
          cargo metadata --no-deps --format-version 1 | jq -r '"homepage=" + .packages[0].homepage' | tee -a $GITHUB_OUTPUT
    outputs:
      name: ${{ steps.crate-metadata.outputs.name }}
      version: ${{ steps.crate-metadata.outputs.version }}
      maintainer: ${{ steps.crate-metadata.outputs.maintainer }}
      homepage: ${{ steps.crate-metadata.outputs.homepage }}

  build-release:
    needs: ['crate-metadata']
    runs-on: ${{ matrix.os }}
    env:
      BUILD_CMD: cargo
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            dpkg_arch: musl-linux-amd64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            dpkg_arch: amd64
          - os: ubuntu-latest
            target: i686-unknown-linux-musl
            dpkg_arch: musl-linux-i686
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            dpkg_arch: i386
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            dpkg_arch: aarch64-unknown-linux-musl
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            dpkg_arch: arm64
          - os: ubuntu-latest
            target: arm-unknown-linux-gnueabihf
            dpkg_arch: armhf
          - os: ubuntu-latest
            target: arm-unknown-linux-musleabihf
            dpkg_arch: musl-linux-armhf
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-cygwin

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        if: matrix.os != 'windows-latest'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install cross
        if: matrix.os == 'ubuntu-latest' && matrix.target != ''
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Use cross
        if: matrix.os == 'ubuntu-latest' && matrix.target != ''
        shell: bash
        run: echo "BUILD_CMD=cross" >> $GITHUB_ENV

      - name: Install msys2 and Rust
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            rust

      - name: Build
        if: matrix.os != 'windows-latest'
        shell: bash
        run: $BUILD_CMD build --locked --profile release-lto --target=${{ matrix.target }}

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: $BUILD_CMD build --locked --profile release-lto --target=${{ matrix.target }}

      - name: Set binary name and path
        id: bin
        shell: bash
        run: |
          EXE_suffix=""
          if [[ ${{ matrix.os }} = windows-* ]]
          then
            EXE_suffix=".exe"
          fi

          BIN_NAME="${{ needs.crate-metadata.outputs.name }}${EXE_suffix}"
          BIN_PATH="target/${{ matrix.target }}/release-lto/${BIN_NAME}"
          echo "BIN_NAME=${BIN_NAME}" >> $GITHUB_OUTPUT
          echo "BIN_PATH=${BIN_PATH}" >> $GITHUB_OUTPUT

      - name: Smoke test
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          $BUILD_CMD run --profile release-lto --locked --target=${{ matrix.target }} -- list-scopes

      - name: Smoke test (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          $BUILD_CMD run --profile release-lto --locked --target=${{ matrix.target }} -- list-scopes

      - name: Generate shell completions
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          $BUILD_CMD run --profile release-lto --locked --target=${{ matrix.target }} -- completion --output-file "_${{ needs.crate-metadata.outputs.name }}"

      - name: Generate shell completions (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          $BUILD_CMD run --profile release-lto --locked --target=${{ matrix.target }} -- completion --output-file "_${{ needs.crate-metadata.outputs.name }}"

      - name: Create tarball
        id: package
        shell: bash
        run: |
          PKG_suffix=".tar.gz";
          if [[ ${{ matrix.os }} = windows-* ]]
          then
            PKG_suffix=".zip"
          fi
          PKG_BASENAME=${{ needs.crate-metadata.outputs.name }}-v${{ needs.crate-metadata.outputs.version }}-${{ matrix.target }}
          PKG_NAME="${PKG_BASENAME}${PKG_suffix}"
          echo "PKG_NAME=${PKG_NAME}" >> $GITHUB_OUTPUT

          PKG_STAGING="package"
          ARCHIVE_DIR="${PKG_STAGING}/${PKG_BASENAME}/"
          mkdir -p "${ARCHIVE_DIR}"

          # Binary
          cp "${{ steps.bin.outputs.BIN_PATH }}" "$ARCHIVE_DIR"

          # README, LICENSE, and CHANGELOG
          cp "README.md" "LICENSE" "CHANGELOG.md" "$ARCHIVE_DIR"

          # Shell completions
          mkdir "${ARCHIVE_DIR}/completion"
          cp "_${{ needs.crate-metadata.outputs.name }}" "${ARCHIVE_DIR}/completion"

          # base compressed package
          pushd "${PKG_STAGING}/" >/dev/null
          if [[ ${{ matrix.os }} = windows-* ]]
          then
            7z -y a "${PKG_NAME}" "${PKG_BASENAME}"/* | tail -2
          else
            tar czf "${PKG_NAME}" "${PKG_BASENAME}"/*
          fi
          popd >/dev/null

          # Let subsequent steps know where to find the compressed package
          echo "PKG_PATH=${PKG_STAGING}/${PKG_NAME}" >> $GITHUB_OUTPUT

      - name: Create Debian package
        id: debian-package
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          # COPYRIGHT_YEARS="2026 - "$(date "+%Y")
          COPYRIGHT_YEARS="2026"
          DPKG_STAGING="debian-package"
          DPKG_DIR="${DPKG_STAGING}/dpkg"
          mkdir -p "${DPKG_DIR}"

          DPKG_BASENAME=${{ needs.crate-metadata.outputs.name }}
          DPKG_CONFLICTS=${{ needs.crate-metadata.outputs.name }}-musl
          case ${{ matrix.target }} in *-musl*) DPKG_BASENAME=${{ needs.crate-metadata.outputs.name }}-musl ; DPKG_CONFLICTS=${{ needs.crate-metadata.outputs.name }} ;; esac;
          DPKG_VERSION=${{ needs.crate-metadata.outputs.version }}
          DPKG_ARCH="${{ matrix.dpkg_arch }}"
          DPKG_NAME="${DPKG_BASENAME}_${DPKG_VERSION}_${DPKG_ARCH}.deb"
          echo "DPKG_NAME=${DPKG_NAME}" >> $GITHUB_OUTPUT

          # Binary
          install -Dm755 "${{ steps.bin.outputs.BIN_PATH }}" "${DPKG_DIR}/usr/bin/${{ steps.bin.outputs.BIN_NAME }}"

          # Autocompletion files
          install -Dm644 _${{ needs.crate-metadata.outputs.name }} "${DPKG_DIR}/usr/share/zsh/vendor-completions/_${{ needs.crate-metadata.outputs.name }}"

          # README, LICENSE, and CHANGELOG
          install -Dm644 "README.md" "${DPKG_DIR}/usr/share/doc/${DPKG_BASENAME}/README.md"
          install -Dm644 "LICENSE" "${DPKG_DIR}/usr/share/doc/${DPKG_BASENAME}/LICENSE"
          install -Dm644 "CHANGELOG.md" "${DPKG_DIR}/usr/share/doc/${DPKG_BASENAME}/CHANGELOG.md"

          cat > "${DPKG_DIR}/usr/share/doc/${DPKG_BASENAME}/copyright" <<EOF
          Format: http://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
          Upstream-Name: ${{ needs.crate-metadata.outputs.name }}
          Source: ${{ needs.crate-metadata.outputs.homepage }}

          Files: *
          Copyright: ${{ needs.crate-metadata.outputs.maintainer }}
          Copyright: $COPYRIGHT_YEARS ${{ needs.crate-metadata.outputs.maintainer }}

          License: MIT
            Permission is hereby granted, free of charge, to any person obtaining a copy
            of this software and associated documentation files (the "Software"), to deal
            in the Software without restriction, including without limitation the rights
            to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
            copies of the Software, and to permit persons to whom the Software is
            furnished to do so, subject to the following conditions:
            .
            The above copyright notice and this permission notice shall be included in all
            copies or substantial portions of the Software.
            .
            THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
            IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
            AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
            LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
            OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
            SOFTWARE.
          EOF
          chmod 644 "${DPKG_DIR}/usr/share/doc/${DPKG_BASENAME}/copyright"

          # control file
          mkdir -p "${DPKG_DIR}/DEBIAN"
          cat > "${DPKG_DIR}/DEBIAN/control" <<EOF
          Package: ${DPKG_BASENAME}
          Version: ${DPKG_VERSION}
          Section: utils
          Priority: optional
          Maintainer: ${{ needs.crate-metadata.outputs.maintainer }}
          Homepage: ${{ needs.crate-metadata.outputs.homepage }}
          Architecture: ${DPKG_ARCH}
          Provides: ${{ needs.crate-metadata.outputs.name }}
          Conflicts: ${DPKG_CONFLICTS}
          Description: \$ A blazingly fast Zsh syntax highlighter
          EOF

          DPKG_PATH="${DPKG_STAGING}/${DPKG_NAME}"
          echo "DPKG_PATH=${DPKG_PATH}" >> $GITHUB_OUTPUT

          # build dpkg
          fakeroot dpkg-deb --build "${DPKG_DIR}" "${DPKG_PATH}"

      - name: Upload release archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          version="${{ needs.crate-metadata.outputs.version }}"
          gh release upload "$version" ${{ steps.package.outputs.PKG_PATH }}

      - name: "Upload Debian package"
        if: steps.debian-package.outputs.DPKG_PATH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          version="${{ needs.crate-metadata.outputs.version }}"
          gh release upload "$version" ${{ steps.debian-package.outputs.DPKG_PATH }}
