# This file is partly based on the workflows from bat (https://github.com/sharkdp/bat/)
# and ripgrep (https://github.com/BurntSushi/ripgrep). bat is released under the
# MIT license (Copyright (c) 2018-2023 bat-developers) and ripgrep under the
# Unlicense.

name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get the release version from the tag
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Check that tag version and Cargo.toml version are the same
        shell: bash
        run: |
          if ! grep -q "version = \"$VERSION\"" Cargo.toml; then
            echo "version does not match Cargo.toml" >&2
            exit 1
          fi
    outputs:
      version: ${{ env.VERSION }}

  build-release:
    needs: ['check-version']
    runs-on: ${{ matrix.os }}
    env:
      BUILD_CMD: cargo
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: i686-unknown-linux-musl
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: arm-unknown-linux-gnueabihf
          - os: ubuntu-latest
            target: arm-unknown-linux-musleabihf
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-cygwin

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        if: matrix.os != 'windows-latest'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install cross
        if: matrix.os == 'ubuntu-latest' && matrix.target != ''
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Use cross
        if: matrix.os == 'ubuntu-latest' && matrix.target != ''
        shell: bash
        run: echo "BUILD_CMD=cross" >> $GITHUB_ENV

      - name: Install msys2 and Rust
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            rust

      - name: Build
        if: matrix.os != 'windows-latest'
        shell: bash
        run: $BUILD_CMD build --locked --profile release-lto --target=${{ matrix.target }}

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: $BUILD_CMD build --locked --profile release-lto --target=${{ matrix.target }}

      - name: Set binary name and path
        id: bin
        shell: bash
        run: |
          EXE_suffix=""
          if [[ ${{ matrix.os }} = windows-* ]]
          then
            EXE_suffix=".exe"
          fi

          BIN_PATH="target/${{ matrix.target }}/release/zsh-patina${EXE_suffix}"
          echo "BIN_PATH=${BIN_PATH}" >> $GITHUB_OUTPUT

      - name: Smoke test
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          $BUILD_CMD run --profile release-lto --locked --target=${{ matrix.target }} -- list-scopes

      - name: Smoke test
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          $BUILD_CMD run --profile release-lto --locked --target=${{ matrix.target }} -- list-scopes

      - name: Create tarball
        id: package
        shell: bash
        run: |
          PKG_suffix=".tar.gz";
          if [[ ${{ matrix.os }} = windows-* ]]
          then
            PKG_suffix=".zip"
          fi
          PKG_BASENAME=zsh-patina-v${{ needs.check-version.outputs.version }}-${{ matrix.target }}
          PKG_NAME="${PKG_BASENAME}${PKG_suffix}"
          echo "PKG_NAME=${PKG_NAME}" >> $GITHUB_OUTPUT

          PKG_STAGING="package"
          ARCHIVE_DIR="${PKG_STAGING}/${PKG_BASENAME}/"
          mkdir -p "${ARCHIVE_DIR}"

          # Binary
          cp "${{ steps.bin.outputs.BIN_PATH }}" "$ARCHIVE_DIR"

          # README and LICENSE
          cp "README.md" "LICENSE" "$ARCHIVE_DIR"

          # base compressed package
          pushd "${PKG_STAGING}/" >/dev/null
          if [[ ${{ matrix.os }} = windows-* ]]
          then
            7z -y a "${PKG_NAME}" "${PKG_BASENAME}"/* | tail -2
          else
            tar czf "${PKG_NAME}" "${PKG_BASENAME}"/*
          fi
          popd >/dev/null

          # Let subsequent steps know where to find the compressed package
          echo "PKG_PATH=${PKG_STAGING}/${PKG_NAME}" >> $GITHUB_OUTPUT

      - name: Upload release archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          version="${{ needs.check-version.outputs.version }}"
          gh release upload "$version" ${{ steps.package.outputs.PKG_PATH }}
